"""Tamper-evident hash chain over ``audit_events``.

Why this exists
---------------
``audit_events`` is the evidence chain for product traceability: it records who
did what, when. As a plain table it offered no protection at all — anyone with a
SQLite client could ``UPDATE`` or ``DELETE`` a row and every downstream query
would keep answering confidently. A log you cannot prove is unmodified is not
evidence.

The chain
---------
Each row stores the hash of the previous row (``prev_hash``) and its own hash
(``event_hash``), computed as::

    event_hash = sha256(prev_hash + "\\n" + canonical(row fields))

so changing any field of any row breaks every hash after it. ``verify_chain``
walks the ledger in ``id`` order, recomputes each hash, and reports the first row
that does not match — which is the row that was altered, or the one right after
it was deleted.

The database also carries ``BEFORE UPDATE`` / ``BEFORE DELETE`` triggers that
refuse the operation outright, so tampering has to be deliberate (dropping the
triggers) rather than accidental.

Why ``event_id`` and not ``id``
-------------------------------
``id`` is assigned by AUTOINCREMENT, so it is not known until after the INSERT —
and the trigger forbids the follow-up UPDATE that would be needed to fill in the
hash. ``event_id`` is generated by the caller before the insert, so the whole row
including its hash can be written in one statement.

Concurrency
-----------
The chain requires reading the previous tip before inserting. Two inserts that
read the same tip would produce a fork, which verification reports as a break.
``link_event`` therefore runs inside a write transaction; callers that already
hold one (most of them do) keep it, and callers that do not get a short one.

Flask-free, like the other ``traceability`` support modules.
"""

from __future__ import annotations

import hashlib
import sqlite3
from dataclasses import dataclass, field
from typing import Any, Mapping

# The chain starts from "nothing". Any fixed value works as long as it is not a
# plausible hash, so that a chain missing its first row cannot look intact.
GENESIS_HASH = ""

# Fields that participate in the hash, in a fixed order.
#
# ``id`` is excluded (AUTOINCREMENT assigns it after the INSERT, so it is not
# known when the hash is computed). ``event_id`` is included and is unique, so
# the hash still commits to this specific row.
HASHED_FIELDS: tuple[str, ...] = (
    "event_id",
    "event_type",
    "object_type",
    "object_code",
    "related_object_code",
    "station_id",
    "station_name",
    "operator_name",
    "actor_user_id",
    "reason",
    "payload_json",
    "occurred_at",
)

TRIGGER_NO_UPDATE = "audit_events_no_update"
TRIGGER_NO_DELETE = "audit_events_no_delete"


def _value(fields: Any, name: str) -> Any:
    """Read a field from a dict (at insert time) or a ``sqlite3.Row`` (at verify time).

    ``sqlite3.Row`` has no ``.get()``, so both shapes have to be handled here
    rather than at every call site.
    """
    if isinstance(fields, Mapping):
        return fields.get(name)
    try:
        return fields[name]
    except (IndexError, KeyError, TypeError):
        return None


def canonical_entry(fields: Any) -> str:
    """Deterministic serialisation of the hashed fields.

    ``None`` and ``""`` must not hash differently: ``actor_user_id`` is NULL for
    system actions and would otherwise change value across a round trip.
    """
    lines = []
    for name in HASHED_FIELDS:
        value = _value(fields, name)
        lines.append(f"{name}={'' if value is None else value}")
    return "\n".join(lines)


def compute_event_hash(prev_hash: str, fields: Mapping[str, Any]) -> str:
    material = f"{prev_hash}\n{canonical_entry(fields)}"
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


def chain_tip(connection: sqlite3.Connection) -> str:
    """The most recent ``event_hash``, or the genesis value on an empty ledger."""
    row = connection.execute(
        "SELECT event_hash FROM audit_events ORDER BY id DESC LIMIT 1"
    ).fetchone()
    if row is None:
        return GENESIS_HASH
    return str(row["event_hash"] or GENESIS_HASH)


def link_event(connection: sqlite3.Connection, fields: Mapping[str, Any]) -> tuple[str, str]:
    """Return ``(prev_hash, event_hash)`` for a row about to be inserted.

    Opens a short ``BEGIN IMMEDIATE`` when the caller is not already in a
    transaction, so two concurrent inserts cannot both extend the same tip.
    """
    opened = False
    if not connection.in_transaction:
        connection.execute("BEGIN IMMEDIATE")
        opened = True
    try:
        prev = chain_tip(connection)
        digest = compute_event_hash(prev, fields)
        if opened:
            connection.execute("COMMIT")
        return prev, digest
    except Exception:
        if opened:
            connection.execute("ROLLBACK")
        raise


@dataclass
class ChainReport:
    ok: bool
    total: int
    verified: int
    first_broken_id: int | None = None
    first_broken_reason: str = ""
    unhashed: int = 0
    tip: str = ""
    problems: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "ok": self.ok,
            "total": self.total,
            "verified": self.verified,
            "firstBrokenId": self.first_broken_id,
            "firstBrokenReason": self.first_broken_reason,
            "unhashed": self.unhashed,
            "tip": self.tip,
            "problems": self.problems,
        }


def verify_chain(connection: sqlite3.Connection) -> ChainReport:
    """Recompute the whole ledger and report the first row that does not match."""
    rows = connection.execute(
        "SELECT id, event_hash, prev_hash, " + ", ".join(HASHED_FIELDS) +
        " FROM audit_events ORDER BY id ASC"
    ).fetchall()

    total = len(rows)
    unhashed = 0
    expected_prev = GENESIS_HASH
    verified = 0

    for row in rows:
        stored_hash = str(row["event_hash"] or "")
        stored_prev = str(row["prev_hash"] or "")

        if not stored_hash:
            # A row from before the ledger existed, or one inserted outside the
            # application. Either way it is not covered by the chain.
            unhashed += 1
            expected_prev = stored_hash
            continue

        if stored_prev != expected_prev:
            return ChainReport(
                ok=False,
                total=total,
                verified=verified,
                first_broken_id=int(row["id"]),
                first_broken_reason=(
                    "前一条哈希不匹配：记录中的 prev_hash 与上一条的 event_hash 不一致，"
                    "说明该行之前有记录被删除、插入或被改动"
                ),
                unhashed=unhashed,
                tip=str(rows[-1]["event_hash"] or "") if rows else "",
            )

        recomputed = compute_event_hash(expected_prev, row)
        if recomputed != stored_hash:
            return ChainReport(
                ok=False,
                total=total,
                verified=verified,
                first_broken_id=int(row["id"]),
                first_broken_reason="内容哈希不匹配：该行字段被修改过",
                unhashed=unhashed,
                tip=str(rows[-1]["event_hash"] or "") if rows else "",
            )

        expected_prev = stored_hash
        verified += 1

    problems: list[str] = []
    if unhashed:
        problems.append(f"{unhashed} 条记录未纳入哈希链（早于 v21 或由外部写入）")

    return ChainReport(
        ok=not problems,
        total=total,
        verified=verified,
        unhashed=unhashed,
        tip=expected_prev,
        problems=problems,
    )
